### ISSUE TITLE
Too many/few vscores

### ISSUE THREAD

**Issue by sej7278** [willemcvu/kicad-panelizer#3]
When you add vrails on e.g. a 2x2 panel, you get 3 vscores horizontally.

however when you use hrails instead, you don't get 3 vscores vertically - only the centre one. surely this is wrong, as you wouldn't be able to remove the hrails.

also you don't need vscores on the outside edges of the panel unless you're using rails, so a 2x2 panel with no rails only needs the two centre vscores surely - otherwise you're putting vscores where the Edge.Cuts are.

See https://imgur.com/a/rHpOcPZ for visual explanation.

this patch fixes those issues (can't do a PR as my master diverges too much now) and as a side-effect also allows you to have both edge rails (although that's weird!):

```diff
 v_scores = []
 
 # vertical v-scores
-for x in range(1,NUM_X):
+if HORIZONTAL_EDGE_RAIL_WIDTH >0:
+    rangeStart = 0
+    rangeEnd = NUM_X+1
+else:
+    rangeStart = 1
+    rangeEnd = NUM_X
+
+for x in range(rangeStart, rangeEnd):
     x_loc = panelCenter.x - panelWidth/2 + HORIZONTAL_EDGE_RAIL_WIDTH*SCALE + boardWidth*x
     v_score_line = pcbnew.DRAWSEGMENT(board)
     v_scores.append(v_score_line)
@@ -197,7 +204,14 @@ for x in range(1,NUM_X):
     board.Add(v_score_text)
 
 # horizontal v-scores
-for y in range(0,NUM_Y+1):
+if VERTICAL_EDGE_RAIL_WIDTH >0:
+    rangeStart = 0
+    rangeEnd = NUM_Y+1
+else:
+    rangeStart = 1
+    rangeEnd = NUM_Y
+
+for y in range(rangeStart, rangeEnd):
     y_loc = panelCenter.y - panelHeight/2 + VERTICAL_EDGE_RAIL_WIDTH*SCALE + boardHeight*y
     v_score_line = pcbnew.DRAWSEGMENT(board)
     v_scores.append(v_score_line)
```

**Comment by willemcvu** [comment]
At this point, you're actively developing this script much more than I ever will, and your copy has gotten quite a bit beyond my copy, and I actually just used your copy instead of mine to panelize and ship a production board. I think it would be best for me to hand over control of this script to you, and then put a note in my readme that mine is depreciated, and point to yours.

There are just a couple of features that I want to add, and I can totally fork and do PR's on your repo for those. Specifically the features I plan on adding when I get time:

 - Tooling holes - fiducials and 3mm holes on rails (mostly written)
 - Ability to specify a maximum panel size and then calculate NUM_X and NUM_Y off of that, since most cheap board houses (JLCPCB etc) have a special deal for boards under e.g. 100x100mm (not written but trivial to implement).
    -  I think the best way to do this would be to make the NUM_X and NUM_Y command-line arguments optional, then add a switch and two additional PANEL_WIDTH and PANEL_HEIGHT. If neither [NUM_X and NUM] or [PANEL_WIDTH and PANEL_HEIGHT] are defined, then throw an error.

**Comment by sej7278** [comment]
its up to you re. forking. i think i'm done with changes for now and you did the heavy lifting ;-)

i was thinking something similar about calculating how many boards you can get on a 100x100 panel, makes more sense to do that than to specify NUM_X and NUM_Y for most cases.

pcbway also confirmed the prefer vscores on the Edge.Cuts layer, which raises some issues i mentioned in README.md - would be interesting to see if the board you just sent over gets panelized ok.

**Comment by sej7278** [comment]
just when i said i was done you got me thinking!

so here's a test branch that calculates the number of boards that will fit on a specified panel size: https://github.com/sej7278/kicad-panelizer/tree/calc_panelsize

```
./panelizer.py --panelx=100 --panely=100 --hrail=5 --hrailtext=JLCJLCJLCJLC rs232b.kicad_pcb 
You can fit 2 x 2 boards on the panel
Board dimensions: 37.134002x40.690002mm
Panel dimensions: 84.368006x81.480006mm
```

i've not done anything fancy like trying to rotate the boards to see if they'd fit better on a panel.

i wonder if we should include a sample (basic) pcb for people to test against - that way we control the pcb that bugs are reported against and can rule it out as the cause.

edit: fixed alignment of "V-SCORE" text so no matter the size its always after the end of the vscore lines (was on TODO list)
